title: Planificación del Proyecto
description: Documentación de la asignatura.
remote_theme: just-the-docs/just-the-docs


search_enabled: true


aux_links:
  "Repositorio del Proyecto":
    - "https://github.com/Azael-uva/planificacion-pdsc"

scss: just-the-docs-custom
