title: Planificaci칩n del Proyecto
description: Documentaci칩n de la asignatura.
remote_theme: just-the-docs/just-the-docs

# Esto activa el buscador integrado
search_enabled: true

# Configuraci칩n b치sica del tema
aux_links:
  "Repositorio del Proyecto":
    - "https://github.com/Azael-uva/tu-repositorio"
